### ISSUE TITLE
Restrictions for sWEPS are not working

### ISSUE THREAD

**Issue by Bryantdl7** [Weol/URM#1]
![image](https://cloud.githubusercontent.com/assets/5564661/10063960/95d8afac-6241-11e5-90ee-9383912a56cb.png)
As you can see in the photo, it warns me that it is restricted but still spawns the weapon

**Comment by Bryantdl7** [comment]
Along with this, using mouse3 on the swep in the spawnlist will override the restriction, and spawning it normally by using mouse1 in the weapons tab also overrides the restriction

**Comment by Weol** [comment]
Hmm... I fail in recreating this issue. Are you using any other addons that might interfere with spawning them. What addons are you using?
