### ISSUE TITLE
Unsafe call CheckLimit() with maybe non exist variable

### ISSUE THREAD

**Issue by DBotThePony** [Weol/URM#11]
https://github.com/Weol/URM/blob/master/lua/ulx/modules/hooks.lua#L173

https://git.dbot.serealia.ca/dbot/dpp/issues/13

Do something like this - https://github.com/garrynewman/garrysmod/blob/master/garrysmod/lua/includes/modules/cvars.lua#L123

**Comment by Weol** [comment]
The function call itself in my source is safe, the problem here lies in that URM will call CheckLimit with arguments that the conventional CheckLimit function was made for. Hooks in URM calls it with prop models, entity classes, vehicle names, etc.

DPP's CheckLimit function expects conventional sandbox limits, but URM hooks still call it with prop models and more. It looks like DPP has its own limit system, so this looks like a standard addon conflict error; you're running two different limit systems on one server.

**Comment by DBotThePony** [comment]
DPP replaces default `CheckLimit()` function of `playerMetaTable` with its own for allowing modifying absolute limit edits for stuff. You just call `CheckLimit()` with MUCH non exists variables.

**Comment by Weol** [comment]
Hmm, I'm not sure exactly what causes that error. But one thing is clear; when URM and DPP override the same function, a conflict occurs. In the issue you linked, you said it started happening after the latest commit to DPP, so the author probably recently added or changed something that causes the overrides to conflict.

**Comment by DBotThePony** [comment]
I AM the creator of DPP. And i fixed a bug where CheckLimit() wasn't being overriden and thus, SandBox limits wasn't working. And you are calling `CheckLimit()` with non exist variable - https://git.dbot.serealia.ca/dbot/dpp/blob/master/lua/dpp/sh_hooks.lua#L561 Example - sbox_maxweapon_crowbar

`offtopic` - When making an importer URM->DPP i found this https://github.com/Weol/URM/blob/master/lua/ulx/modules/restrictions.lua#L45-L46

```
[DBot's VLL] [ADMIN MESSAGE] SERVERSIDE LUA ERROR: Invalid console variable to check player limit. WTF? sbox_maxmodels/props_c17/FurnitureRadiator001a.mdl is a not existing variable
Contact your addon author first, BEFORE contacting with DPP author.
[DBot's VLL] [ADMIN MESSAGE] stack traceback:
	VLL:647: in function 'ErrorHandler'
	VLL:642: in function 'error'
	[VLL: dpp - dpp/sh_init.lua]:141: in function 'ThrowError'
	[VLL: dpp - dpp/sh_hooks.lua]:561: in function 'CheckLimit'
	addons/urm/lua/ulx/modules/hooks.lua:46: in function 'fn'
	addons/ulysses/lua/ulib/shared/hook.lua:109: in function 'Call'
	gamemodes/sandbox/gamemode/commands.lua:167: in function 'GMODSpawnProp'
	gamemodes/sandbox/gamemode/commands.lua:27: in function <gamemodes/sandbox/gamemode/commands.lua:8>
	lua/includes/modules/concommand.lua:54: in function <lua/includes/modules/concommand.lua:49>

yea
```

**Comment by Weol** [comment]
That would explain why this started happening after the latest update. There is nothing I can do on my side, as URM won't work without its own CheckLimit(). The conclusion is that these addons are are incompatible.

**Comment by DBotThePony** [comment]
@ickycoolboy
