### ISSUE TITLE
attempt to index a nil value

### ISSUE THREAD

**Issue by Bryantdl7** [Weol/URM#3]
[ERROR] addons/urm/lua/ulx/xgui/settings/xgui_restrictions.lua:262: attempt to index a nil value
1. DoClick - addons/urm/lua/ulx/xgui/settings/xgui_restrictions.lua:262
   1. unknown - lua/vgui/dlabel.lua:218

**Comment by Weol** [comment]
Thank you for reporting this. It seems to be becasue you have not selected an item to edit from the item list. I will add a failsafe for it, so that it does not produce and error. If howerver, you had an item from the item list (the huge list) selected, please let me know.

**Comment by Bryantdl7** [comment]
You are correct I had nothing selected, it's more of a cosmetic bug.
