### ISSUE TITLE
[Bug] Github version of ulx and ulib breaks this addon possibly

### ISSUE THREAD

**Issue by ickycoolboy** [Weol/URM#4]
It will say "this (whatever) has been restricted), however you can still spawn it.

**Comment by Weol** [comment]
This means that another addon is interfering with URM. Any addon that uses the "PlayerSpawn" hooks badly will override URM.

**Comment by ickycoolboy** [comment]
I first tested the version of ulib and ulx from these two links:
http://ulyssesmod.net/archive/ulx/ulx-v3_62.zip
http://ulyssesmod.net/archive/ULib/ULib-v2_52.zip

The restrictions worked fine with these versions.

I then tested with the github version of ulx and ulib from these two links:
https://github.com/Nayruden/Ulysses.git/trunk/ulx
https://github.com/Nayruden/Ulysses.git/trunk/ulib

The restrictions no longer worked.

**Comment by Weol** [comment]
It appears you are right. I cannot however locate the problem, until I do, I suggest you use the version from their website.

**Comment by Weol** [comment]
This has been fixed.
