### ISSUE TITLE
[Feature request] Adv dupe item restrictions

### ISSUE THREAD

**Issue by ickycoolboy** [Weol/URM#5]
Can an option be added to prevent things being spawned by advanced duplicator 1 and 2 so people can't spawn blacklisted items with adv dupe?

**Comment by Weol** [comment]
Unfortunately, Adv. Dupe. 1 & 2 don't have a hook that checks if a player is allowed to duplicate something. Its therefore difficult to do.

I cannot see how it could be done without any changes in the Adv. Dupe. addons.

**Comment by ickycoolboy** [comment]
Another Restriction addon for ulx called URS has the ability to do this feature. Here is the link: https://github.com/Aaron113/urs

**Comment by Weol** [comment]
Oh, Advanced duplicator has a hook. I've must have missed it when I was examining its source code. I will add Adv. Dupe 1 & 2 support.

Thank you.

**Comment by Weol** [comment]
It has been added.

**Comment by ickycoolboy** [comment]
I have been told by my players that limits that I have set for the amount of items they can spawn now work with advdupe, but they can still spawn blacklisted items.

**Comment by Weol** [comment]
Adv. Dupe 2 or Adv. Dupe 1?

**Comment by ickycoolboy** [comment]
Adv dupe 2

**Comment by ickycoolboy** [comment]
Well after a while. Blacklisted items are now, blacklisted. However limits are not followed. For example, if i set the entity limit to 5. Someone could use advdupe 2 to soar past that.
