### ISSUE TITLE
[CRITICAL BUG] Recent update crippled addon

### ISSUE THREAD

**Issue by ickycoolboy** [Weol/URM#7]
The problem is within restrictions.lua. I reverted it back to the initial version from when the addon is created and it fixed it.

The symptoms are no one can spawn anything and people spawn with no weapons at all.

This is an example error:
[ERROR] addons/urm-master/lua/ulx/modules/restrictions.lua:48: attempt to index field 'WhiteListWeapons' (a nil value)
1. CheckRestrictions - addons/urm-master/lua/ulx/modules/restrictions.lua:48
   1. PlayerSpawnSWEP - addons/urm-master/lua/ulx/modules/hooks.lua:165
   2. fn - addons/urm-master/lua/ulx/modules/hooks.lua:197
      1. unknown - addons/ulib/lua/ulib/shared/hook.lua:179
      2. Give - [C]:-1
      3. RunClass - gamemodes/sandbox/gamemode/player_class/player_sandbox.lua:56
      4. Call - gamemodes/base/gamemode/player.lua:317
         1. PlayerSpawn - gamemodes/base/gamemode/player.lua:274
         2. unknown - gamemodes/sandbox/gamemode/init.lua:41

This is a link to the full log file with more errors:
http://puu.sh/kVbd4/b1fda57bdc.txt

**Comment by Weol** [comment]
I added a failsafe, so this should now be fixed.

Thank you for reporting it.

**Comment by ickycoolboy** [comment]
My server is filled with players right now, I will test this fix when the server empties a bit :)

**Comment by ickycoolboy** [comment]
Alright I just tested it and the error doesn't occur anymore. Thank you.
