### ISSUE TITLE
[Suggestion] Small cosmetic change 

### ISSUE THREAD

**Issue by ickycoolboy** [Weol/URM#8]
Instead of saying "this [Blank]  has been restricted" have it say "this [blank] has been restricted from your rank." 

The reason of this is because some players think that most things on the server are restricted from everyone. I know how to make this change, but it gets overwritten whenever the addon updates.

**Comment by Weol** [comment]
Sure, that can be done.

**Comment by ickycoolboy** [comment]
Thank you for the change :)
